"""empty message

Revision ID: 59b1884bcbe5
Revises: fa1613fd7b06
Create Date: 2023-10-25 11:15:53.964050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b1884bcbe5'
down_revision = 'fa1613fd7b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_people_id_fkey', type_='foreignkey')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorite_people_id_fkey', 'people', ['people_id'], ['id'])

    # ### end Alembic commands ###
