"""empty message

Revision ID: 993fa241d99f
Revises: c3b08f282a4c
Create Date: 2023-10-25 10:40:27.876368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993fa241d99f'
down_revision = 'c3b08f282a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=250), nullable=False),
    sa.Column('id_tipo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favoritos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('id_tipo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='favoritos_pkey')
    )
    op.drop_table('favorite')
    # ### end Alembic commands ###
